apiVersion: v1
kind: Service
metadata:
  name: go-echo-nodeport
spec:
  type: NodePort
  selector:
    app: go-echo
  ports:
    - protocol: TCP
      port: 80          # Porta interna do serviço
      targetPort: 8080  # Porta onde o Go está ouvindo
      nodePort: 30007   # Porta exposta em todos os nós (opcional fixar)